<?php

namespace Innova\PathBundle\Entity;

/**
 * CriteriagroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriteriagroupRepository extends \Doctrine\ORM\EntityRepository
{
}
